spring:
  application:
    name: redis
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 60  # ttl duration
      cache-null-values: false
server:
  port: 8088

logging:
  level:
    org:
      example:
        redis: DEBUG